# Generated by Django 5.0.6 on 2026-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_application_registration_expiry_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ownership_type',
            field=models.CharField(choices=[('sole', 'Sole Ownership'), ('joint', 'Joint Ownership'), ('company', 'Company')], default='sole', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationapproval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proprietor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
